FlexBox 구현한다
dry-frontend/dry-design-system pull request #10
Opened 2023-04-29 07:52 UTC by liswktjs

close #9 

flex옵션을 사용하기 쉽도록 FlexBox컴포넌트를 구현하였습니다 

## 구현 내용 
- FlexBox 컴포넌트 생성 
- forward Ref를 활용하여 Ref값도 넣을 수 있도록 구현 
- 스토리북에서 controls로 props를 수정하여 간단하게 경험해볼 수 있도록 구현 
- direction, justify-content, align-items, gap, width, height등은 Props로 수정 가능하게 하고 나머지 값들의 경우에는 인라인 style Props으로 유저가 지정할 수 있게 구현 

## 추가 사항 

개인적으로 flex 를 사용할 때 가운데 정렬을 많이하는 것 같아서 기본 옵션으로 가운데 정렬을 주었습니다 
여러분의 기호를 듣고 싶네요 하하 

구현 사항을 확인하기 위해서는 storybook을 실행시켜서 봐주세요!

2023-05-01 10:19 UTC, soyi47 requested changes
파일 이름만 RC 입니다. 다른 코멘트는 읽어보고 반영하고 싶은 부분만 반영해주세요~ 🙏

2023-05-01 10:19 UTC, soyi47 commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +`;
파일 이름 styles 말고 `_.styled.tsx`로 수정해주세요~!

2023-05-01 10:19 UTC, soyi47 commented on packages/payment/src/components/flexBox/FlexBox.tsx
> +    | 'right';
```
direction?: React.CSSProperties['flexDirection'];
justifyContent?: React.CSSProperties['justifyContent'];
...
```
요런 식도 가능할 것 같아요!

2023-05-01 10:19 UTC, soyi47 commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +  gap: ${({ gap }) => gap};
아래처럼 스타일드 컴포넌트에서 기본값을 주고 prop 내려 받아 Container에 넣을 때는 스타일 관련 props를 spread해서 바로 넣어줘도 좋을 것 같습니다. 요건 취향차이인 것 같아서 샐리가 하고 싶은대로~!
```
width: ${({ width }) => width | '100%'};
```

2023-05-01 13:08 UTC, yunjin-kim requested changes
🫡고생했슈🫡

2023-05-01 13:08 UTC, yunjin-kim commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +  height: ${({ height }) => height};
굳이 width와 height를 props로 받는 이유가 있나요?
보통 내부 element와 padding으로 처리했던 것 같은데 차라리 padding값을 받는게 낫지 않을까요?

2023-05-02 14:18 UTC, liswktjs commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +`;
아하 습관이 되어버려서 잠시 잊었네요 하핫

2023-05-02 14:21 UTC, liswktjs commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +  height: ${({ height }) => height};
flexbox를 범용적인 컴포넌트라고 생각했고 제가 만약 이 컴포넌트를 사용한다고 한다면 부모 컴포넌트로 자식 컴포넌트를 감싸는 용도로 사용하지 않을까 라고 가정하고 만드는 과정에서 width와 height는 있어야 한다고 생각했습니다

width 100%로나 100vw로 화면에 꽉 차게 고정할 수도 있고요!

2023-05-02 14:25 UTC, liswktjs commented
> 파일 이름만 RC 입니다. 다른 코멘트는 읽어보고 반영하고 싶은 부분만 반영해주세요~ 🙏
> 
> +) 컴포넌트 폴더명도 대문자로 시작하도록 수정해주세요!

@soyi47   github가 대소문자 구분 안 한다고 file changed되기를 거부하는데 우짜죠....ㅠ

2023-05-03 01:52 UTC, yunjin-kim commented on packages/payment/src/components/flexBox/FlexBox.styles.tsx
> +  height: ${({ height }) => height};
width 속성을 넣지 않더라도 default로 width 100%가 들어갑니다. 
부모 컴포넌트로 자식 컴포넌트를 감싸는 과정에서 width, height가 필요한지는 잘 모르겠네요. 근데 필수값은 아니라서 샐리 생각처럼 해도 괜찮을 것 같네요!

2023-05-03 01:52 UTC, yunjin-kim approved these changes

2023-05-08 16:27 UTC, soyi47 approved these changes
> github가 대소문자 구분 안 한다고 file changed되기를 거부해서 components 밑에 common 폴더 하나 새로 팠습니다

그거... Git 옵션 있을텐데... 한번 찾아보십쇼
암튼 수정 확인! 어프루브 하겠습니다 👍

2023-05-14 11:50 UTC, merged