FlexBox, Text, Stepper 컴포넌트 구현
dry-frontend/dry-design-system pull request #16
Opened 2023-04-29 11:38 UTC by compy-ryu

진행 현황 공유를 위해, Draft로 PR 올려둡니덩.
작업 완료 시 채널 통해서 멘션 드릴께요

---

- [ ] FlexBox 컴포넌트를 구현한다.
  - [ ] Storybook에서 조회할 수 있어야한다.
- [ ] Text 컴포넌트를 구현한다.
  - [ ] Storybook에서 조회할 수 있어야한다.
- [ ] Stepper 컴포넌트를 구현한다.
  - [ ] 비제어 컴포넌트를 지원한다.
  - [ ] 제어 컴포넌트를 지원한다.
  - [ ] (선택) 증가/감소 시 애니메이션을 제공한다.
  - [ ] 코드를 리팩토링한다.
  - [ ] Storybook에서 조회할 수 있어야한다.

2023-05-02 01:30 UTC, notPotter requested changes
안녕하세요 콤피~ 구현하느라 고생많으셨습니다!!
핵심인 것 같은 `stepper` 위주로 몇가지 코멘트 남겼습니다!
확인하시고 반영 or 역으로 궁금하신 점 남겨주세요!

2023-05-02 01:30 UTC, frontend-jihyeok-um commented on packages/cart/src/components/Button/PlainButton.tsx
이 버튼은 스타일을 제거한 기본버튼 느낌인가요?

2023-05-02 01:30 UTC, frontend-jihyeok-um commented on packages/cart/src/components/FlexBox/FlexBox.stories.tsx
> +import { useRef, useState } from 'react';
사용하지 않는 import는 제거해줍시다!

2023-05-02 01:30 UTC, frontend-jihyeok-um commented on packages/cart/src/components/Stepper/Stepper.tsx
> +          value={value ? value : undefined}
`null`이 아니라 직접 `undefined`를 사용하신 이유가 있나요?

2023-05-02 01:30 UTC, frontend-jihyeok-um commented on packages/cart/src/components/Stepper/Stepper.tsx
> +            onAnimationEnd={() => setPreviousAction(undefined)}
여기도요!

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/styles.ts
> +export const SpringAnimation = styled.div<{ status: Actions; count: number }>`
저희가 `framer-motion`을 사용하게 되었으니 한 번 활용해 보심이 어떨지 가볍게 제안드려봅니다!

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  return (
아래에서 말했던 `framer-motion`활용에 대해서 가볍게 리뷰 남겨보겠습니다!

```tsx
  return (
    <FlexBox direction="row">
      <S.InputWrappedFlexBox>
        <AnimatePresence mode="wait">
          {previousAction?.action === 'INCREASE' && (
            <S.CurrentNumberTextField
              key={textFieldRef.current?.value}
              initial={{ opacity: 0, y: -100 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: 100 }}
              transition={{ duration: 0.2 }}
              ref={setRefs}
              type="number"
              min={min}
              max={max}
              value={value ? value : undefined}
              defaultValue={defaultValue}
            />
          )}

          {previousAction?.action !== 'INCREASE' && (
            <S.CurrentNumberTextField
              key={textFieldRef.current?.value}
              initial={{ opacity: 0, y: 100 }}
              animate={{ opacity: 1, y: 0 }}
              exit={{ opacity: 0, y: -100 }}
              transition={{ duration: 0.2 }}
              ref={setRefs}
              type="number"
              min={min}
              max={max}
              value={value ? value : undefined}
              defaultValue={defaultValue}
            />
          )}
        </AnimatePresence>
      </S.InputWrappedFlexBox>

      <FlexBox>
        <S.ControlButton type="button" onClick={handleClickToChange('INCREASE')}>
          <FontAwesomeIcon icon={faCaretUp} />
        </S.ControlButton>

        <S.ControlButton type="button" onClick={handleClickToChange('DECREASE')}>
          <FontAwesomeIcon icon={faCaretDown} />
        </S.ControlButton>
      </FlexBox>
    </FlexBox>
  );
```

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  return (
```tsx
export const CurrentNumberTextField = styled(motion.input)`
  appearance: textfield;
  width: 100%;
  height: 100%;

  border: none;
  outline: none;
  padding: 0;
  background-color: unset;

  text-align: center;
  font-size: 18px;

  &:focus {
    outline: none;
  }

  &:disabled {
    color: #000;
    background-color: #fff;
  }

  &::-webkit-outer-spin-button,
  &::-webkit-inner-spin-button {
    display: none;
    appearance: none;
    margin: 0;
  }
`;
```

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  value?: React.InputHTMLAttributes<HTMLInputElement>['value'];
확실히 타입을 관리 포인트 적게 활용을 잘하시네요!
배워가겠습니다!

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  return (
아예 완전히 동작하도록 바꾼 예시는 아니라서
만약 바꾸시게되면 비제어에서 애니메이션이 제대로 동작하도록 
조금 손을 보셔야할 것 같습니다 ㅎㅎ

2023-05-02 01:30 UTC, notPotter commented on packages/cart/src/components/Stepper/Stepper.tsx
> +          <FontAwesomeIcon icon={faCaretUp} />
혹시 이 `<FontAwesomeIcon icon={faCaretUp} />` 컴포넌트가
콤피가 말했던 `svg`를 이용하는 방식인가요??

2023-05-02 02:43 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  value?: React.InputHTMLAttributes<HTMLInputElement>['value'];
헐 좀 민망헌디... 이거 마지막줄 다른 방식으로 테스트해두다 냄겨둔거에요...ㅋㅋㅋㅋㅋ
extends & value 없어도 됩니더...

2023-05-02 11:57 UTC, frontend-jihyeok-um commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  value?: React.InputHTMLAttributes<HTMLInputElement>['value'];
헐 필요없는 값이었군요.. ㅋㅋㅋㅋㅋㅋ 저는 제어컴포넌트에서 받아쓰는 값인 줄 알았네요

2023-05-04 09:07 UTC, al-bur commented on packages/cart/src/components/Text/Text.tsx
> +`;
혹시 이거에 대해서 조금 설명 가능할까요???

위에 h1& 같은 경우는 Text컴포넌트가 h1 태그의 하위요소로 사용되었을 때의 스타일링 방법이라는 것을 알게되었는데, &&&의 역할은 잘 이해가 안되서요ㅠㅠ

2023-05-04 12:43 UTC, al-bur commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  const isControlComponent = Boolean(value);
```suggestion
  const isControlledComponent = Boolean(value);
```

어떤가요ㅎㅎ

2023-05-04 12:52 UTC, al-bur commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  onDecrease?: React.MouseEventHandler<HTMLButtonElement>;
오호 핸들러랑 구분하기 위해서 한 칸 뛰워준 건가요

2023-05-04 12:54 UTC, al-bur commented on packages/cart/src/components/Stepper/Stepper.tsx
> +import * as S from './styles';
wow...이렇게도 할 수 있군요

2023-05-04 13:10 UTC, al-bur reviewed
콤피 고생했어요~~
생각보다 stepper가 비제어를 내부에서 컨트롤 해줘야해서....힘들었겠네요!!

2023-05-05 07:28 UTC, compy-ryu commented on packages/cart/src/components/Button/PlainButton.tsx
맞아유! 가끔 브라우저 별로 버튼 스타일이 제각각이라
매번 적용해주는 것보다는 이렇게 기본 버튼 컴포넌트 만들고 확장해가는게 좋더라구요!

2023-05-05 07:29 UTC, compy-ryu commented on packages/cart/src/components/Button/PlainButton.tsx
이상하게 제거 안했는데 계속 Outdated가 뜨네요...

2023-05-05 07:29 UTC, compy-ryu commented on packages/cart/src/components/FlexBox/FlexBox.stories.tsx
> +import { useRef, useState } from 'react';
완료했슴덩!!

2023-05-05 07:35 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +          value={value ? value : undefined}
아.. 여기도 이전 비제어 처리하면서 변경 전 코드가 그대로 남아있는 부분임더.. 허허

큰 의미는 없고, 서버에서 보통 값 내려줄 때 빈 값으로 전달할 때 `null`으로 전달하는 케이스가 많았다보니
클라이언트랑 서버 값 출처 구분하려고 습관적으로 undefined 쓰는거 같습니다.

일단 요거 제거할께요!

2023-05-05 07:37 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +            onAnimationEnd={() => setPreviousAction(undefined)}
상동임더. 혹시 해리가 null을 원한다면 null으로 바꿔드릴 수 있읍니다.

2023-05-05 08:44 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  return (
헐, 저희 framer 쓰기로 했었쥬;;;

해리가 제안해준 방식은 비제어 컴포넌트에서 value 유지가 되지 않는 이슈가 발생되어
useAnimation hook 써서 구현해보았습니더!

- 8685d180b4f1cedbaff63659b42cfdaf1ae4db1b

2023-05-05 08:46 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +          <FontAwesomeIcon icon={faCaretUp} />
네 맞슴더!!!

폰트어썸이 svg 기반으로 하고, 쓰는 아이콘만 뽑아서 사용하다보니 빌드 용량도 절약할 수 있슴덩
겸사 겸사 사이트에서 필요한 아이콘들 쉽게 찾아 볼 수 있어서 쓰고 있어요

https://fontawesome.com/

업데이트도 꾸준하고 아이콘도 많아서 추천하는 라이브러리에유

2023-05-05 08:55 UTC, compy-ryu commented on packages/cart/src/components/Text/Text.tsx
> +`;
일단 `h1`&은 Text 컴포넌트가 h1 태그를 사용할 때 적용되어라를 의도하고 구현했습니다!
예시입니다!

```jsx
<Text as="h1">캄피입니더</Text>
```

결과
```html
<h1 style="font-size: 32px;">캄피입니더</h1>
```

그리고 만약 아래 케이스도 존재할텐데유
```jsx
<Text as="h1" size={72}>더 큰 폰트로 바꿨어유</Text>
```

이런 경우 css 우선 순위에 따라 h1&이 먼저 스타일이 적용되어서 size prop(`72`)이 적용되지 않습니더!
그래서 `&&&` selector를 쓰면 &&& 쪽이 우선 순위를 가지게 되어 size prop을 적용시킬 수 있게 되어유!


그리고 이렇게 불편하게 Text 컴포넌트를 따로 만든 이유는 FlexBox와 동일한데요.

CSS로 계속해서 font-size, font-weight 이렇게 넣어주다보면 빌드 용량이 쓸모없이 늘지 않을까 해서
컴포넌트로 스타일링 자체를 위임해서 용량을 조금이라도 줄여보는걸 의도하고 만들었슴덩

linaria랑 쓰면 기깔납니다.

2023-05-05 08:56 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  const isControlComponent = Boolean(value);
헛 바꿧습니더!

- 41edf49def813efddea4cec2a13ddd02f9d2d7fa

2023-05-05 08:57 UTC, compy-ryu commented on packages/cart/src/components/Stepper/Stepper.tsx
> +  onDecrease?: React.MouseEventHandler<HTMLButtonElement>;
넵, 개인 취향이지만 핸들러 타입은 대체로 길어질 때가 많다보니 맨 밑에 두고, 한칸씩 띄워둡니더!

2023-05-10 01:38 UTC, merged