Theme을 설정한다
dry-frontend/dry-design-system pull request #2
Opened 2023-04-15 10:00 UTC by liswktjs

close #1 

payments notion에 정리된 theme들을 theme provider를 통해 사용할 수 있도록 구현하였습니다 

## 구현 내용 

- theme 객체 생성
- themeProvider통해 app에 theme 주입 
- storybook에 theme 주입 
- typescript가 theme인식하기  위한 d.ts 구현 

## 추가 사항 
styled-components를 typescript가 인식하지 못하고 있어서 @types/styled-components를 설치하였습니다 
혹시 문제 있으면 제거하겠습니다! 

구현하면서 app과 storybook에서 themeProvider가 정상작동하는 것으로 확인하였지만,
각자 로컬 환경에서도 원활히 작동되는지 추가 확인 부탁드립니다 :)

2023-04-17 08:09 UTC, soyi47 requested changes
샐리 1등! 👏👏👏👏👏

코멘트만 반영해주세요~
빠르게 테마 컬러 설정해주셔서 감사합니다! 🤗

2023-04-17 08:09 UTC, soyi47 commented on packages/payment/src/styles/theme.ts
> +  PRIMARY: ' #2AC1BC',
공백이 있는 것 같아요~ 🧐

2023-04-17 08:09 UTC, soyi47 commented on packages/payment/src/styles/theme.ts
> +};
대문자로 통일하고 6자리 표기 맞추면 어떨까요?

2023-04-17 08:09 UTC, soyi47 commented on packages/payment/src/styles/theme.ts
> +  PRIMARY_SOFT: '##04C09E',
#이 2개여요~

2023-04-19 10:52 UTC, yunjin-kim approved these changes
👍

2023-04-19 10:52 UTC, yunjin-kim commented on packages/payment/src/styles/theme.ts
> +  BLACK_500: '#111',
2222

2023-04-22 07:59 UTC, liswktjs commented on packages/payment/src/styles/theme.ts
> +  PRIMARY: ' #2AC1BC',
오라라 공백이 들어가있군요 바로 제거하겠습니당

2023-04-22 08:01 UTC, liswktjs commented on packages/payment/src/styles/theme.ts
> +  PRIMARY_SOFT: '##04C09E',
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ이때 졸렸나보군요

2023-04-23 04:04 UTC, soyi47 approved these changes
확인완료~ 어프루브! 👏👏👏

2023-04-23 04:10 UTC, merged