UnderlinedHeader 컴포넌트를 구현한다.
dry-frontend/dry-design-system pull request #25
Opened 2023-05-02 07:51 UTC by soyi47

## 작업 내용
- UnderlinedHeader 컴포넌트를 만들었습니다.
- h3 태그를 이용하고 밑줄은 border-bottom 으로 스타일링 했습니다.
- fontSize는 디자인 시안대로 16px, fontWeight는 prop으로 줄 수 있도록 prop에 추가했습니다.
- 디자인따라 폰트 색상을 주려다 보니 theme colors에 중간 색상을 추가했는데요. 작업하면서 필요한 색상 계속 추가하고, 마지막에 숫자 단위 정리 다시하면 좋을 것 같습니다.
- 🧐 width에 따라 밑줄 길이 달라지도록 width도 prop으로 받을 수 있게 했는데... 이게 맞나 싶네요. 아이디어 주십쇼

스토리북 확인해보시고 수정 의견 주세요!

closed #20

2023-05-02 15:00 UTC, liswktjs requested changes
width에는 props이 최선인 것 같습니다 하핫

2023-05-02 15:00 UTC, liswktjs commented on packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.stories.tsx
> +    fontWeight: {
```
width : {
    control:'text'
}
```

width 도 argsTypes에 추가해서 controls에 직접 입력해볼 수 있도록 하면 좋을 것 같아요!

2023-05-02 15:00 UTC, liswktjs commented on packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.tsx
> +}
<img width="245" alt="스크린샷 2023-05-02 오후 11 59 00" src="https://user-images.githubusercontent.com/60773373/235705119-5bb97489-0d94-46a6-b2e8-82b0fc891703.png">
개인적으로 underlineHeader에  현재 그림과 같은 highlight부분이 더 긴 경우에 글자를 가운데 정렬을 할 수 있는 옵션을 주는 것이 어떨까 생각합니다

2023-05-06 07:17 UTC, yunjin-kim approved these changes
고생하셨습니다~! 
리뷰에 대한 반영은 솦이 결정해주세요^^

2023-05-06 07:17 UTC, yunjin-kim commented on packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.tsx
> +}
lineColor를  props로 받아 사용하는 측에서 color를 결정하는 것처럼 font도 받는건 어떤가요?

2023-05-07 05:24 UTC, soyi47 commented on packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.tsx
> +}
반영했습니당!
[feat: fontColor, textAlign props 추가](https://github.com/dry-frontend/dry-design-system/pull/25/commits/af431e8b798b5869d6f5363f61ea4ac220fec634)

2023-05-07 05:24 UTC, soyi47 commented on packages/payment/src/components/UnderlinedHeader/UnderlinedHeader.stories.tsx
> +    fontWeight: {
반영완료!
[feat: fontColor, textAlign props 추가](https://github.com/dry-frontend/dry-design-system/pull/25/commits/af431e8b798b5869d6f5363f61ea4ac220fec634)

2023-05-09 12:35 UTC, liswktjs approved these changes

2023-05-09 12:35 UTC, merged