ColorChipButton 컴포넌트를 구현한다.
dry-frontend/dry-design-system pull request #26
Opened 2023-05-02 08:36 UTC by soyi47

## 작업 내용
- ColorChipButton 컴포넌트를 만들었습니다.
- 디자인에 gradient가 들어간 경우가 있어서, Gradient prop(true/false)을 추가했습니다.

스토리북 확인해보시고 수정 의견 주세요!

closed #23

2023-05-02 15:10 UTC, liswktjs reviewed
utils 함수로 분리해서 출시해주는 거 어떤가요 후후

2023-05-02 15:10 UTC, liswktjs commented on packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
> +import { theme } from 'styles/theme';
혹시 ColorChipButtonProps import 문을 theme과 바꿔주실수있나여 
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ ./가 맨 밑에 있어야만 할 것 같은 느낌적인 느낌이에여

2023-05-02 15:10 UTC, liswktjs commented on packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
> +};
오호 styled코드에서 함수도 같이 선언하시는 스타일이시군요 

저희 프로젝트의 규모가 한정적이라 해당 함수가 현재 프로젝트 내에서 다른 곳에 재 사용 될 일은 거의 없을 것 같네요 그래도 함수 내용만 놓고 보면 얼마든지 재사용이 가능한 유틸 함수라고 생각이 드네요 
따로 분리해서 디자인 시스템 낼 때 유틸 함수로 제공해주죠 키키

2023-05-02 15:10 UTC, liswktjs commented on packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
> +`;
제가 일하는 곳에서 이런식으로 props로 값을 넘겨주게 되면 아무래도 스타일이 바뀔때마다 class name생성하는데 연산이 들어가서 className으로 조정하는 것 보다 성능상으로 불이익이 있다고 하네요 

물론 저희 프로젝트에서는 실시간으로 스타일이 바뀌지 않고 성능 저하도 될 일이 없지만... 
그냥 약간의 잡설이였습니다

2023-05-06 07:26 UTC, yunjin-kim requested changes

2023-05-06 07:26 UTC, yunjin-kim commented on packages/payment/src/components/ColorChipButton/ColorChipButton.tsx
> +  text?: string;
chipColor와 text를 optional로 받는 이유가 있을까요?
colorChip에는 반드시 필요한 props라고 생각해서요!

2023-05-08 14:48 UTC, soyi47 commented on packages/payment/src/components/ColorChipButton/ColorChipButton.tsx
> +  text?: string;
오 처음에는 Default value를 주면 괜찮지 않나 했는데
다시 생각해보니까 필수로 받는 게 좋을 것 같네요! 수정했습니다! [feat: props 수정](https://github.com/dry-frontend/dry-design-system/pull/26/commits/311f7b63f16e58e4840721cf417262401f7468ae)

2023-05-08 14:48 UTC, soyi47 commented on packages/payment/src/components/ColorChipButton/ColorChipButton.styled.tsx
> +import { theme } from 'styles/theme';
수정 완료! [feat: props 수정](https://github.com/dry-frontend/dry-design-system/pull/26/commits/311f7b63f16e58e4840721cf417262401f7468ae)

2023-05-09 12:36 UTC, yunjin-kim approved these changes
👍👍👍

2023-05-09 12:37 UTC, liswktjs approved these changes

2023-05-09 12:38 UTC, merged