feat: Carousel 구현
dry-frontend/dry-design-system pull request #27
Opened 2023-05-03 13:37 UTC by soyi47

## 작업 내용
- Carousel 컴포넌트를 만들었습니다.
- 컴포넌트에 children으로 들어오는 요소들을 하나씩 보여주도록 구현했습니다.
- 버튼으로만 동작하게 구현했어요. (드래그로 넘기는 기능은 후순위)

스토리북 확인해보시고 수정 의견 주세요!

closed #18

2023-05-06 07:43 UTC, yunjin-kim requested changes

2023-05-06 07:43 UTC, yunjin-kim commented on packages/payment/src/assets/arrow@2x.png
화살표는 svg 형식은 어떤가요? 
png 형식으로 하신 이유가 있을까요?

2023-05-06 07:43 UTC, yunjin-kim commented on packages/payment/src/components/Carousel/Carousel.tsx
> +            <li>{item}</li>
key 값 붙여주지 않아도 warning 안 뜨던가요?

2023-05-06 07:43 UTC, yunjin-kim commented on packages/payment/src/components/Carousel/Carousel.tsx
> +const Carousel = ({ children }: CarouselProps) => {
button 클릭할 때 함수가 실행될 수 있도록 props를 받는건 어떤가요?

2023-05-06 14:33 UTC, liswktjs requested changes
결과 비슷한 리뷰입니당!

2023-05-06 14:33 UTC, liswktjs commented on packages/payment/src/components/Carousel/Carousel.tsx
> +const Carousel = ({ children }: CarouselProps) => {
버튼을 클릭할 때마다 상태를 바꾸는 등의 액션을 유저가 추가하고 싶을 수 있으니깐 그와 관련된 대응을 해주면 좋을 것 같아요

2023-05-08 14:55 UTC, soyi47 commented on packages/payment/src/components/Carousel/Carousel.tsx
> +            <li>{item}</li>
오 그러네요? warning 뜨진 않는데 index 값으로 key 값 추가했습니다. 
[feat: CarouselProps 수정 및 key 추가](https://github.com/dry-frontend/dry-design-system/pull/27/commits/8f2fd3b877d1d672bce899e716ab6e22dfede189)

2023-05-08 14:55 UTC, soyi47 commented on packages/payment/src/components/Carousel/Carousel.tsx
> +const Carousel = ({ children }: CarouselProps) => {
수정 완료~
[feat: CarouselProps 수정 및 key 추가](https://github.com/dry-frontend/dry-design-system/pull/27/commits/8f2fd3b877d1d672bce899e716ab6e22dfede189)

2023-05-08 14:55 UTC, soyi47 commented on packages/payment/src/components/Carousel/Carousel.tsx
> +const Carousel = ({ children }: CarouselProps) => {
수정 완료~
[feat: CarouselProps 수정 및 key 추가](https://github.com/dry-frontend/dry-design-system/pull/27/commits/8f2fd3b877d1d672bce899e716ab6e22dfede189)

2023-05-08 14:56 UTC, soyi47 commented on packages/payment/src/assets/arrow@2x.png
별 이유 없슴다
svg로 변경했슴다! [refactor: 화살표 이미지 svg로 변경](https://github.com/dry-frontend/dry-design-system/pull/27/commits/a50d93f259d95337dea31891c7a80a95392791fd)

2023-05-09 12:38 UTC, yunjin-kim approved these changes
👍👍👍

2023-05-09 12:47 UTC, liswktjs commented
disabled 상태를 추가해주세요!

2023-05-11 07:59 UTC, soyi47 commented
@yunjin-kim @liswktjs 
disabled 추가했습니다. 확인해보시고 괜찮으면 머지해주세요! [feat: 버튼 disabled 케이스 추가](https://github.com/dry-frontend/dry-design-system/pull/27/commits/160b571d995868985f16aa52cf0322b2ded4713d)

2023-05-14 11:52 UTC, liswktjs approved these changes

2023-05-15 06:52 UTC, merged