Checkbox 컴포넌트를 구현한다.
dry-frontend/dry-design-system pull request #28
Opened 2023-05-05 08:43 UTC by soyi47

## 작업 내용
- Checkbox 컴포넌트를 만들었습니다.

코드랑 스토리북 확인해보시고 수정 의견 주세요!

closed #21

2023-05-06 07:47 UTC, yunjin-kim approved these changes
👍👍

2023-05-06 07:47 UTC, yunjin-kim approved these changes
👍👍

2023-05-06 14:35 UTC, liswktjs requested changes

2023-05-06 14:35 UTC, liswktjs commented on packages/payment/src/components/Checkbox/Checkbox.styled.tsx
> +  appearance: none;
-wekit-appearance와 같은 것도 안 챙겨 주어도 상관없나요?
크로스 브라우징 이슈가 있을지 궁금하네용

2023-05-08 15:01 UTC, soyi47 commented on packages/payment/src/components/Checkbox/Checkbox.styled.tsx
> +  appearance: none;
오 좋아요~ 크롬에서 정상 동작 확인하긴 했는데 추가하는 게 좋을 것 같네요.
수정했습니다. [feat: style 코드 수정](https://github.com/dry-frontend/dry-design-system/pull/28/commits/9e5915d5c1e151d09c360b7b751b7a10a8e8d1c6)

2023-05-09 12:48 UTC, liswktjs approved these changes

2023-05-09 12:48 UTC, merged