Drawer 컴포넌트를 구현한다
dry-frontend/dry-design-system pull request #29
Opened 2023-05-05 12:01 UTC by liswktjs

close #19 

Drawer 컴포넌트를 구현하였습니다 

## 구현 내용 

- isOpen 값을 boolean으로 받아 drawer의 열림 여부를 보여준다  
  - isOpen이 true일 경우 animation을 통해 drawer가 열린다 
- anchor 
  - 방향을 정해서 열리게 할 수 있다 

## 궁금한 점 

- width와 height를 유저가 커스텀할 수 있도록 해야하는 것 아닌 가 라는 생각이 듭니당 의견 주세유!

2023-05-08 15:39 UTC, soyi47 requested changes
> width와 height를 유저가 커스텀할 수 있도록 해야하는 것 아닌 가 라는 생각이 듭니당 의견 주세유!

사용자가 drawer 내부에 넣는 요소의 width나 height와 동일하게 가지도록 할 수 없으려나요?
직접 drawer 컴포넌트에 어떤 Prop을 주기보다 내부 요소를 자유롭게 스타일링하고 거기에 따라 drawer가 움직이는게 사용하기 편할 것 같아서요!
`fit-content` 같은 값을 적용할 수 있을지 한번 보면 좋을 것 같슴다.

2023-05-08 15:39 UTC, soyi47 commented on packages/payment/src/components/Drawer/Drawer.stories.tsx
> +    }
radio로 보여주는 거 어때요?!
```suggestion
    anchor: {
      defaultValue: 'bottom',
      description: 'drawer가 열리는 방향에 따라서 값을 조정할 수 있습니다',
      control: {
        type: 'radio'
      },
      options: ['top', 'bottom', 'left', 'right']
    }
```

2023-05-09 03:57 UTC, yunjin-kim requested changes

2023-05-09 03:57 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.styled.tsx
> +          border-radius: 10px 10px 0 0;
config로 빼는게 깔끔하지 않을까요?

2023-05-09 03:57 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.styled.tsx
> +  height: 0;
왜 필요한건가요?

2023-05-09 03:57 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, anchor, children }: PropsWithChildren<DrawerProps>) => {
dimmer에 클릭 이벤트 부착하는건 어떤가요?

2023-05-09 03:57 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.tsx
> +    </S.Dimmed>
Container가 Dimmed에 감싸져있을 필요가 있을까요?

2023-05-09 08:49 UTC, yunjin-kim requested changes

2023-05-09 08:49 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.tsx
> +      <S.Container className={isOpen ? 'is-open' : ''} anchor={anchor}>
isOpen가 내부에서 필요한가요?

2023-05-14 11:56 UTC, liswktjs commented on packages/payment/src/components/Drawer/Drawer.styled.tsx
> +  height: 0;
이제와 돌이켜보니 이유가 생각나지 않습니다... 일단 제거하겠습니다 👍

2023-05-14 11:57 UTC, liswktjs commented on packages/payment/src/components/Drawer/Drawer.styled.tsx
> +          border-radius: 10px 10px 0 0;
config로 뺀다는 것이 어떤 의미일까요?

2023-05-14 11:57 UTC, liswktjs commented on packages/payment/src/components/Drawer/Drawer.tsx
> +const Drawer = ({ isOpen, anchor, children }: PropsWithChildren<DrawerProps>) => {
오 좋은 생각입니다!

2023-05-14 12:02 UTC, liswktjs commented on packages/payment/src/components/Drawer/Drawer.tsx
> +    </S.Dimmed>
Container 컴포넌트 위치를 고정시켜야해서 dimmer로 감싸는 것이 편리하다고 생각하였습니다 
추가로 유저가 어떤 위치에 Drawer를 위치 시킬지 변수가 많다고 생각해서 dimmer랑 set로 이동시키는 것이 좋다고 생각했습니다!

2023-05-14 12:03 UTC, liswktjs commented on packages/payment/src/components/Drawer/Drawer.tsx
> +      <S.Container className={isOpen ? 'is-open' : ''} anchor={anchor}>
isOpen을 통해서 Drawer가 열릴 때 드르릭 하는 애니메이션을 구현하기 위해 넣어주었습니다!

2023-05-16 08:58 UTC, yunjin-kim commented on packages/payment/src/components/Drawer/Drawer.styled.tsx
> +          border-radius: 10px 10px 0 0;
제 pr에서 확인 부탁드립니다.

2023-05-17 14:03 UTC, soyi47 requested changes
> > width와 height를 유저가 커스텀할 수 있도록 해야하는 것 아닌 가 라는 생각이 듭니당 의견 주세유!
> 
> 사용자가 drawer 내부에 넣는 요소의 width나 height와 동일하게 가지도록 할 수 없으려나요? 직접 drawer 컴포넌트에 어떤 Prop을 주기보다 내부 요소를 자유롭게 스타일링하고 거기에 따라 drawer가 움직이는게 사용하기 편할 것 같아서요! `fit-content` 같은 값을 적용할 수 있을지 한번 보면 좋을 것 같슴다.

요거 반영 되었나요?

2023-05-21 05:17 UTC, yunjin-kim approved these changes

2023-05-21 09:56 UTC, merged