ToolTip컴포넌트를 구현한다
dry-frontend/dry-design-system pull request #31
Opened 2023-05-05 15:05 UTC by liswktjs

close #30 

ToolTip 컴포넌트를 구현한다 

## 구현사항 

- props
   - position : tooltip hover시 보여질 description이 나올 위치를 지정할 수 있다 
   - gap : tooltip mark와 description이 얼마나 떨어질지 정할 수 있다 
- children 
    - 버튼을 커스텀해서 넣을 수 있다 
    - description 컴포넌트를 직접 넣을 수 있다 

## 공유 사항 

아무래도, description 컴포넌트도 tooltip Icon 컴포넌트와 마찬가지로 유저가 직접 커스텀할 할 수 있는 방향이 좋을 것 같아서 compound component 패턴을 활용하여 구현하였습니다 

## 구조 
```
<Container> -> ToolTip을 감싸는 부모 컴포넌트로 position relative를 적용해야합니다  
    <ToolTip position={'right' | 'left' | 'top' | 'bottom'} gap={string}>
        <ToolTip.IconWrapper>
             <div>?</div> -> 유저가 넣고 싶은 아이콘 넣기
        </ToolTip.IconWrapper>
        <ToolTip.DescriptionWrapper>
              <div>설명</div> -> 유저가 넣고 싶은 description 컴포넌트 넣어주기 
        </ToolTip.DescriptionWrapper>
      </ToolTip>
</Container>
```

2023-05-08 15:53 UTC, soyi47 requested changes
position right에 gap이 0px이면 툴팁 아이콘 바로 오른쪽에 붙어서 description이 나오는 걸 예상했는데요! 아이콘을 덮어버리네요. ㅠㅇㅠ

<img width="1176" alt="image" src="https://user-images.githubusercontent.com/71116429/236869889-aae96891-3688-4e79-883c-a03c089a03bb.png">

position right인데도 gap을 마이너스 값을 줘야하는건 좀 이상한 거 같습니다.
<img width="1206" alt="image" src="https://user-images.githubusercontent.com/71116429/236870668-3cdaa440-d41e-44b4-9650-18ffc05a67ce.png">

1. 기본적으로 툴팁 아이콘을 가리지 않는 곳에 description이 위치하고,
2. position 방향에 따라 gap도 같은 방향으로 잡혀야하는 게 아닌가 싶어요!

2023-05-08 15:53 UTC, soyi47 commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +import ToolTipContext from './tooltipContext';
파일명 대문자 맞춰주세요!

2023-05-08 15:53 UTC, soyi47 commented on packages/payment/src/components/ToolTip/TooltipContext.tsx
> +} | null>(null);
ToolTip Context로 구현한 이유가 있나요? Context 안 써도 되지 않나 싶어서요!

2023-05-08 15:53 UTC, soyi47 commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +  gap: string;
제 취향으로는 gap 기본 값이 있고, prop으로 주어지는 경우에는 사용자가 넣은 gap을 적용해주면 좋을 것 같아요!

2023-05-09 10:19 UTC, yunjin-kim requested changes

2023-05-09 10:19 UTC, yunjin-kim commented on packages/payment/src/components/ToolTip/ToolTip.styled.tsx
> +export const DescriptionWrapper = styled.div<{
<img width="135" alt="스크린샷 2023-05-09 오후 5 58 56" src="https://user-images.githubusercontent.com/79692272/237047321-6f449f22-e9a3-4e33-ac52-7e42c3e4d463.png">

이런 표족한 화살표 같은게 있는게 좋지 않을까요?

2023-05-09 10:19 UTC, yunjin-kim commented on packages/payment/src/components/ToolTip/ToolTip.styled.tsx
> +
이것도 객체로 따로 빼는게 좋지 않을까요?

2023-05-09 10:19 UTC, yunjin-kim commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +  };
함수 한 개로 할 수 있지 않을까요?

2023-05-14 12:09 UTC, liswktjs commented on packages/payment/src/components/ToolTip/TooltipContext.tsx
> +} | null>(null);
유저가 ? 와 같은 아이콘이 들어가는 tooltip 컴포넌트, description 들을 커스텀해서 넣어줘야 한다고 생각했습니다 
정해진 스타일을 주는 것 보다 일정의 스타일은 유저가 커스텀하게 해주어야 한다고 생각했어요! 
추가적으로 왼쪽 오른쪽 위 아래를 모두 고려하다보니 경우의 수가 많아져서 compound component 패턴으로 하는 것이 더 낫겠다고 판단해서 상태를 공유해야하는 것은 context로 모두 넣었습니다

2023-05-14 12:13 UTC, liswktjs commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +import ToolTipContext from './tooltipContext';
수정하면서 파일 확장자 ts로 수정하였습니다

2023-05-14 12:22 UTC, liswktjs commented
> position right에 gap이 0px이면 툴팁 아이콘 바로 오른쪽에 붙어서 description이 나오는 걸 예상했는데요! 아이콘을 덮어버리네요. ㅠㅇㅠ
> 
> <img alt="image" width="1176" src="https://user-images.githubusercontent.com/71116429/236869889-aae96891-3688-4e79-883c-a03c089a03bb.png">
> 
> position right인데도 gap을 마이너스 값을 줘야하는건 좀 이상한 거 같습니다. <img alt="image" width="1206" src="https://user-images.githubusercontent.com/71116429/236870668-3cdaa440-d41e-44b4-9650-18ffc05a67ce.png">
> 
> 1. 기본적으로 툴팁 아이콘을 가리지 않는 곳에 description이 위치하고,
> 2. position 방향에 따라 gap도 같은 방향으로 잡혀야하는 게 아닌가 싶어요!

해당 케이스 들을 개발하면서 마주하면서 여러가지 방법을 시도하다가 현재의 방법으로 이루어지게 되었습니다 일단 문제점은 아래와 같습니다 
1. 유저가 tooltip ? 아이콘과 description을 커스텀해서 넘겨준다 
=> 현재 코드를 작성하는 시점에서 유저가 어떤 크기의 툴팁을 넣어줄지 예측하기 힘들어서 스타일링 경우의 수가 너무 많아지게 됩니다. 아마도 제가 커스텀해서 width와 height크기를 지정해준다면 이 문제는 해결 될 것 같습니다 
2. 위 아래 왼쪽 오른쪽 모든 방향으로 커스텀이 가능하다 
=> 1번과 더불어서 compound component 패턴으로 개발하게 되면서 유저가 어떤 순서로 컴포넌트를 넣어줘야할지 예측하기 힘들어졌습니다. 유저가 아이콘을 먼저 넣고 description을 넣어줄 수도 있고 description을 넣고 icon을 먼저 넣을 수도 있는 상황에서 각각의 상황에서 Right, left값을 유저가 커스텀해야하는 필요가 생깁니다 넣는 순서에 따라서 스타일링 방법이 달라져서입니다. 
그래서 tooltip이 먼저 description이  그 다음이라는 순서를 strict한 규칙으로 정하지 않는 이상 유저가 직접 gap위치를 수정할 수 밖에 없는 상황에 있습니다 

그래서 흠... 의견 한 번 주시길 바랍니다! 아직 명확한 해결책은 생각하지 못했네요

2023-05-14 12:24 UTC, liswktjs commented on packages/payment/src/components/ToolTip/ToolTip.styled.tsx
> +export const DescriptionWrapper = styled.div<{
description 컴포넌트 부분은 유저가 커스텀가능하도록 구현하였기 때문에 유저가 원한다면 그렇게 코딩해서 넘겨주면 될 것 같습니다

2023-05-14 12:25 UTC, liswktjs commented on packages/payment/src/components/ToolTip/ToolTip.styled.tsx
> +
어떻게 한다는 걸까요? 음..... 제가 잘 모르니깐 예시한번 주세요

2023-05-14 12:27 UTC, liswktjs commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +  };
???????어떤 말씀이실까요? 함수 하나에서 case별로 나눠서 코드 작성하라는 걸까요???

2023-05-16 09:01 UTC, yunjin-kim commented on packages/payment/src/components/ToolTip/ToolTip.styled.tsx
> +
제 pr에서 확인 부탁드립니다.

2023-05-16 09:02 UTC, yunjin-kim commented on packages/payment/src/components/ToolTip/ToolTip.tsx
> +  };
setIsHover(prev => !prev)
이걸 말한거였습니다

2023-05-17 13:54 UTC, soyi47 commented on packages/payment/src/components/ToolTip/TooltipContext.tsx
> +} | null>(null);
tooltip 아이콘 정도는 커스텀 하는 것도 괜찮은데, description까지 커스텀하도록 줘서 컴파운드 컴포넌트로 직접 조합해서 쓰도록 하는 건 너무 자유롭지 않나 싶습니다. 개인적으론 ToolTip은 컴파운드 컴포넌트 안 쓰고 컴포넌트 하나로 구현하면 좋을 것 같습니다.

2023-05-17 14:00 UTC, soyi47 requested changes
> 1. 유저가 tooltip ? 아이콘과 description을 커스텀해서 넘겨준다

리뷰 코멘트에도 남겼지만 tooltip 아이콘이랑 description 내용 정도만 커스텀 할 수 있으면 좋을 것 같습니다.

> 2. 위 아래 왼쪽 오른쪽 모든 방향으로 커스텀이 가능하다
컴파운드 컴포넌트를 사용함으로 오히려 사용자가 신경써야 할 부분들이 많은 것 같아요. 🥲 컴파운드 컴포넌트 때문에 컨텍스트를 사용하게 되는 부분도 있고요. 그래서 컴포넌트 하나로 만들고 Tooltip description이 나타나는 방향만 사용자가 지정할 수 있게끔 해주면 좋겠습니다. 이전에 남겼듯 position 방향에 따라 default gap 값이 적절히 지정되어 있어야 한다고 생각합니다. position prop이 있음에도 전혀 다른 방향으로 음수 값을 넣어 gap을 조정하는 건 너무 불편할 것 같아요!

2023-05-17 14:00 UTC, soyi47 commented on packages/payment/src/components/ToolTip/TooltipContext.tsx
> +} | null>(null);
tooltip 아이콘 정도는 커스텀 하는 것도 괜찮은데, description까지 커스텀하도록 줘서 컴파운드 컴포넌트로 직접 조합해서 쓰도록 하는 건 너무 자유롭지 않나 싶습니다. 개인적으론 ToolTip은 컴파운드 컴포넌트 안 쓰고 컴포넌트 하나로 구현하면 좋을 것 같습니다.

2023-05-17 14:00 UTC, soyi47 requested changes
> 1. 유저가 tooltip ? 아이콘과 description을 커스텀해서 넘겨준다

리뷰 코멘트에도 남겼지만 tooltip 아이콘이랑 description 내용 정도만 커스텀 할 수 있으면 좋을 것 같습니다.

> 2. 위 아래 왼쪽 오른쪽 모든 방향으로 커스텀이 가능하다

컴파운드 컴포넌트를 사용함으로 오히려 사용자가 신경써야 할 부분들이 많은 것 같아요. 🥲 컴파운드 컴포넌트 때문에 컨텍스트를 사용하게 되는 부분도 있고요. 그래서 컴포넌트 하나로 만들고 Tooltip description이 나타나는 방향만 사용자가 지정할 수 있게끔 해주면 좋겠습니다. 이전에 남겼듯 position 방향에 따라 default gap 값이 적절히 지정되어 있어야 한다고 생각합니다. position prop이 있음에도 전혀 다른 방향으로 음수 값을 넣어 gap을 조정하는 건 너무 불편할 것 같아요!

2023-05-21 09:56 UTC, merged