Input 컴포넌트를 구현한다
dry-frontend/dry-design-system pull request #32
Opened 2023-05-06 10:02 UTC by liswktjs

close #12

payments에 들어갈 Input 컴포넌트를 구현한다 

## 구현 사항 

- 카드 번호 입력 할 수 있는 Input 
   - compound component pattern으로 구현할 수 있도록 했슴다 
- 카드 만료일을 입력 할 수 있는 Input
    - 카드 만료일을 입력할 수 있는 Number input을 props로 받도록 구현했슴다 
- 카드 소유자 이름 입력 할 수 있는 Input 
- 보안 코드 입력할 수 있는 Input
- 카드 비밀 번호를 입력할 수 있는 Input 
    - 번호를 입력할 수 있는 Input들을 받을 수 있게 함 
    - . 컴포넌트를 기본으로 넣어줌

2023-05-08 16:07 UTC, soyi47 requested changes
Input 컴포넌트는 어떤 방식이 좋을지 아직 잘 감이 안 오네요...
샐리 고생하셨습니다. 리뷰 한번 봐주셔요 👏👏👏

2023-05-08 16:07 UTC, soyi47 commented on packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
> +));
다른 Input은 Container를 감싸서 바로 제공하고 있는데 요 아이는 직접 조합해서 사용하도록 만든 이유가 있나요?

+) 보니까 ExpirationDateInput도 조합해서 사용하는 방식이네요..!
이거 사용법 문서를 잘 써둬야할 것 같아요. 어떤 컴포넌트는 그냥 쓸 수 있고 어떤 컴포넌트는 직접 조합해야 하니까..!

2023-05-08 16:07 UTC, soyi47 commented on packages/payment/src/components/Input/CvcInput/CvcInput.stories.tsx
> +import CvcInput from './CvcInput';
이건 취향인 것 같은데 저는 CVC는 원래 대문자니까 그냥 대문자로 하는 편입니당! ㅋㅋㅋㅋ

2023-05-08 16:07 UTC, soyi47 commented on packages/payment/src/components/Input/PasswordInput/PasswordInput.styled.tsx
> +  background-color: ${({ theme }) => theme.colors.PRIMARY};
요거 사용자가 커스텀할 수 있도록 색상 받으면 어떨까요? 기본은 프라이머리 컬러로 하구!

2023-05-08 16:07 UTC, soyi47 commented on packages/payment/src/components/Input/inputType.ts
> +export type InputAttributesType = HTMLAttributes<HTMLInputElement>;
이거 굳이 타입 정의해야 할까요? 따로 빼둔 이유가 있을까요?

2023-05-09 10:53 UTC, yunjin-kim requested changes

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
> +const Slash = () => {
slash 보다는 dash가 낫지 않을까요?

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
> +));
방벙을 하나로 통일하는게 좋을 것 같습니다. 
미션을 진행하는 사람 입장에서 input을 조합해서 쓸 필요가 있는지는 잘 모르겠어용

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/CvcInput/CvcInput.tsx
> +        <S.CvcInput type="password" ref={forwardRef} maxLength={3} {...rest} autoFocus />
maxlength를 모두 넣든지 아니면 다 넣지 말든지 통일을 하는 편이 좋을 것 같습니다.
저는 넣지 않는 것이 좋을 것 같습니다. 왜냐하면 카드 번호를 보더라도 끝자리가 4자리인 카드가 있고 3자리인 카드가 있듯이 디자인 시스템의 영역보다는 사용자의 영역이지 않을까 싶습니다~

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.stories.tsx
> +  <ExpirationDateInput month={<ExpirationDateInput.Month />} year={<ExpirationDateInput.Year />} />
month와 year input을 props 받아서 처리하는 이유가 궁금합니다~

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/NameInput/NameInput.styled.tsx
> +export const NameInput = styled(Input)`
커서가 input과 너무 붙어있는 느낌이 듭니당..

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/NameInput/NameInput.tsx
> +        <S.NameInput type="text" ref={forwardRef} {...rest} autoFocus />
autoFocus 속성이 달려있는 input도 있고 아닌 input도 있는데 달지 않는 것이 좋지 않을까요?
input들의 배치 순서는 저희가 예상할 수 없기 때문입니다~

2023-05-09 10:53 UTC, yunjin-kim commented on packages/payment/src/components/Input/PasswordInput/PasswordInput.stories.tsx
> +);
사용하는 입장에서 이렇게 코드를 작성해야 하는데 조금은 불편할 것  같은 느낌이 드네요. 
그리고 input을 작성함으로 Dot 이라는 컴포넌트가 포함되어 있다는 것도 인지하기는 어려울 것 같습니다.

2023-05-14 12:39 UTC, liswktjs commented on packages/payment/src/components/Input/CardNumberInput/CardNumberInput.tsx
> +));
조합해서 구현된 경우들은 중간중간 "/"나 "-"와 같은 스타일링 코드가 존재하기 때문입니다 

첫 번째로 Container로 구현하게 되면 refList를 받아야하는 문제점들이 있습니다 저 의미없는 스타일링 컴포넌트에는 focus가 갈 필요가 없기 때문입니다 그래서 focus 에 대해서 조작하게 해주고 + Container로 통일하게 해주려면 refList를 넣어야하는 제한된 상황이였습니다. 그래서  오히려 난이도가 높아질 수도 있고 미션에서 공부하면서 사용되는 것이다 보니 다양한 방법으로 가능하게 해주어야 하지 않을까 라는 생각으로 컴파운드 컴포넌트로 구현하게 되었습니다. 이렇게 하면 유저가 직접 컴포넌트를 커스텀해서 넣으면서 ref를 각각 (제가 과거 미션때 한것 처럼) 변수로 만들어서 해주거나 RefList로 관리를 해주거나 등의 방법을 골라서 사용할 수 있습니다. 

두 번째로 CardNumber와 같은 경우 특히 더 문제였는데요 제가 기억하는 바로는 카드 번호를 입력하면서 동적으로 "-"가 생겼던 것으로 기억합니다 card number를 array로 관리할지 first second thrid등등으로 카드 번호를  상태로 관리할지  "-"를  어떻게 보여주어야 할지 미션때 고민 했던 것으로 기억합니다. (저는 개인적으로 후자를 골랐습니다) 그래서 이런 여러가지를 실험할 수 있는 환경을 가지게 해줄려면 "/" 컴포넌트를 직접 컴파운드 컴포넌트로 넣어 주는게 편리하다고 생각했습니다 

만약 한다면 스토리북이나 Readme에 문서화를 하면 될 것 같습니다

2023-05-14 12:40 UTC, liswktjs commented on packages/payment/src/components/Input/inputType.ts
> +export type InputAttributesType = HTMLAttributes<HTMLInputElement>;
각각의  Input에서 중복적으로 사용하고 있어서 중복적으로 코드 길게 작성하기 싫어서 타입 변수로 뺐습니다~

2023-05-14 12:51 UTC, liswktjs commented on packages/payment/src/components/Input/CvcInput/CvcInput.tsx
> +        <S.CvcInput type="password" ref={forwardRef} maxLength={3} {...rest} autoFocus />
다 빼겠습니다~

2023-05-14 12:51 UTC, liswktjs commented on packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.stories.tsx
> +  <ExpirationDateInput month={<ExpirationDateInput.Month />} year={<ExpirationDateInput.Year />} />
> 조합해서 구현된 경우들은 중간중간 "/"나 "-"와 같은 스타일링 코드가 존재하기 때문입니다
> 
> 첫 번째로 Container로 구현하게 되면 refList를 받아야하는 문제점들이 있습니다 저 의미없는 스타일링 컴포넌트에는 focus가 갈 필요가 없기 때문입니다 그래서 focus 에 대해서 조작하게 해주고 + Container로 통일하게 해주려면 refList를 넣어야하는 제한된 상황이였습니다. 그래서 오히려 난이도가 높아질 수도 있고 미션에서 공부하면서 사용되는 것이다 보니 다양한 방법으로 가능하게 해주어야 하지 않을까 라는 생각으로 컴파운드 컴포넌트로 구현하게 되었습니다. 이렇게 하면 유저가 직접 컴포넌트를 커스텀해서 넣으면서 ref를 각각 (제가 과거 미션때 한것 처럼) 변수로 만들어서 해주거나 RefList로 관리를 해주거나 등의 방법을 골라서 사용할 수 있습니다.
> 
> 두 번째로 CardNumber와 같은 경우 특히 더 문제였는데요 제가 기억하는 바로는 카드 번호를 입력하면서 동적으로 "-"가 생겼던 것으로 기억합니다 card number를 array로 관리할지 first second thrid등등으로 카드 번호를 상태로 관리할지 "-"를 어떻게 보여주어야 할지 미션때 고민 했던 것으로 기억합니다. (저는 개인적으로 후자를 골랐습니다) 그래서 이런 여러가지를 실험할 수 있는 환경을 가지게 해줄려면 "/" 컴포넌트를 직접 컴파운드 컴포넌트로 넣어 주는게 편리하다고 생각했습니다
> 
> 만약 한다면 스토리북이나 Readme에 문서화를 하면 될 것 같습니다

요기 참고해주세요~

2023-05-14 12:53 UTC, liswktjs commented on packages/payment/src/components/Input/NameInput/NameInput.styled.tsx
> +export const NameInput = styled(Input)`
ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ padding 특별히 드리죠...

2023-05-14 12:56 UTC, liswktjs commented on packages/payment/src/components/Input/PasswordInput/PasswordInput.stories.tsx
> +);
Dot을 입력할 수 있도록 수정하였습니다

2023-05-14 12:56 UTC, liswktjs commented on packages/payment/src/components/Input/NameInput/NameInput.tsx
> +        <S.NameInput type="text" ref={forwardRef} {...rest} autoFocus />
흠 rest로 지정받고 있으니깐 일단 다 빼도록 하겠습니다

2023-05-16 09:54 UTC, yunjin-kim commented on packages/payment/src/components/Input/ExpirationDateInput/ExpirationDateInput.stories.tsx
> +  <ExpirationDateInput month={<ExpirationDateInput.Month />} year={<ExpirationDateInput.Year />} />
1.
위에서 설명한 것을 저 나름대로 이해했을 때 의문이 드는게
ExpirationDateInput  이 컴포넌트를 props로 받는게 이해가 안 되네요.
차라리 CardNumberInput 처럼
```
  <ExpirationDateInput>
    <ExpirationDateInput.Month />
    <ExpirationDateInput.Slash />
    <ExpirationDateInput.Year />
  </ExpirationDateInput>
```
이런 형태가 좋지 않을까요?

2.
compound component pattern 은 많이 생각해봤는데요..
사바사가 갈리는 문제인 것 같아서 샐리 편한대로 가도 좋을 것 같습니다

근데 제가 만약에 구현한다면 `ref를 각각 변수로 만들어서 해주거나 RefList` 이 두가지 케이스 모두 구현 가능하도록 만들것 같습니다. 그리고 내부에서 `-` 나 `/`는 고정으로 넣어두거나 동적으로 보일 수 있도록 하고(이 부분은 디자인 시스템 만드는 사람이 구현).

2023-05-21 09:57 UTC, merged