공통 button 컴포넌트 추가한다
dry-frontend/dry-design-system pull request #33
Opened 2023-05-07 07:38 UTC by yunjin-kim

## 작업내용

IconButton, TextButton 구현했습니다.
IconButton에서 disabled 처리가 필요한가? 필요하다면 opacity 조절을 통해 해도 괜찮은가? 이 두 의문이 들긴합니다..!

close #4

2023-05-08 16:18 UTC, soyi47 requested changes
1. 스타일드 컴포넌트 파일명 컨벤션 맞춰주세요!
2. 지금 Opacity로 disabled 처리 해둔 거 같은데, 이왕 해둔 거 이 방식으로 가도 괜찮을 것 같습니다! 👍

고생하셨습니당! 리뷰 확인해주세요! 👏👏👏

2023-05-08 16:18 UTC, soyi47 commented on packages/payment/src/components/buttons/IconButton/IconButton.tsx
> +  onClick?(): void;
저는 보통 요런 Prop에 EventHandler 타입을 주는 편입니당!

2023-05-08 16:18 UTC, soyi47 commented on packages/payment/src/components/buttons/TextButton/TextButton.tsx
> +}
variant가 contained | outlined | text니까
컴포넌트 이름을 그냥 Button으로 하고 contained를 default로 주면 어떨까요?

2023-05-08 16:18 UTC, soyi47 commented on packages/payment/src/components/buttons/TextButton/style.ts
> +`;
사용자가 주요 컬러를 커스텀할 수 있도록 prop을 제공해야하려나?! 필요 없으려나?! 싶은 생각이 듭니다

2023-05-09 11:01 UTC, yunjin-kim commented on packages/payment/src/components/buttons/IconButton/IconButton.tsx
> +  onClick?(): void;
```
  onClick?(): ReactEventHandler<HTMLButtonElement>;
```
이렇게를 의미하는 것이 맞을까요?

2023-05-09 11:06 UTC, yunjin-kim commented on packages/payment/src/components/buttons/TextButton/style.ts
> +`;
그 고민을 안 한건 아닌데...color를 받을지 말지는 payment 컴포넌트 모두 통일하는 것이 좋을 것 같습니다. 그래서 회의 때 결정하시죠!

2023-05-09 11:15 UTC, yunjin-kim commented on packages/payment/src/components/buttons/TextButton/TextButton.tsx
> +}
좋습니다~

2023-05-11 08:01 UTC, soyi47 commented on packages/payment/src/components/buttons/IconButton/IconButton.tsx
> +  onClick?(): void;
onClick?: React.MouseEvent<HTMLButtonElement>;

저는 요런 식으로 줍니다! 취향인 것도 같으니 참고만 하셔요!

2023-05-14 13:09 UTC, liswktjs requested changes
회의때 color custom 관련 논의가 있었는데 결이 한 코드를 보면 color를 선택 가능하게 하는 것도 힘든 작업이 될 것 같네요...혹시 어떻게 하기로 결정하셨나요? (뭐가 됐든 화이팅!)

2023-05-14 13:09 UTC, liswktjs commented on packages/payment/src/components/buttons/Button/Button.tsx
> +type ButtonVariant = 'contained' | 'outlined' | 'text';
variant 타입에 만들어 두신 ButtonVariant 적용하면 좋을 것 같습니다 !

2023-05-14 13:09 UTC, liswktjs commented on packages/payment/src/components/buttons/Button/Button.tsx
> +export const buttonColorSet: ButtonStylesConfig = {
아 제 리뷰에서 이렇게 하라는 말이였나요ㅋㅋㅋㅋㅋㅋㅋㅋㅋ

2023-05-14 13:09 UTC, liswktjs commented on packages/payment/src/components/buttons/Button/Button.styled.ts
> +    };
요기 color custom가능하게 되면 바뀌는 코드이나요?

2023-05-14 13:09 UTC, liswktjs commented on packages/payment/src/components/buttons/Button/Button.tsx
> +      disabled: 'GRAY_200'
관련 컬러 설정한거 바뀌는 건가요? 아니면 이대로 가시는 건가요? 회의 때 말한게 가물가물 하네요

2023-05-15 07:41 UTC, yunjin-kim commented on packages/payment/src/components/buttons/Button/Button.tsx
> +export const buttonColorSet: ButtonStylesConfig = {
넵 그렇습니다

2023-05-15 07:42 UTC, yunjin-kim commented on packages/payment/src/components/buttons/Button/Button.styled.ts
> +    };
아뇹 아직 color를 사용측에서 받는 코드는 없는 상태라서

2023-05-15 07:42 UTC, yunjin-kim commented on packages/payment/src/components/buttons/Button/Button.tsx
> +      disabled: 'GRAY_200'
노션에 적혀있는 것을 보면 primary color 정도만 받기로 했습니당

2023-05-16 08:12 UTC, yunjin-kim commented on packages/payment/src/components/buttons/IconButton/IconButton.tsx
> +  onClick?(): void;
```
onClick?: React.MouseEventHandler<HTMLButtonElement>;
```
이 타입으로 변경했습니다. 
  onClick?(): React.MouseEvent<HTMLButtonElement>; <- 이 타입은 반환타입이 `React.MouseEvent<HTMLButtonElement>;` 이것을 의미해서 올바르지 못한 타입이였네요.

2023-05-21 09:57 UTC, merged