Card 를 구현한다.
dry-frontend/dry-design-system pull request #35
Opened 2023-05-07 10:27 UTC by yunjin-kim

### 작업내용

card 컴포넌트 구현했습니다. 딱히 특이사항은 없는 것 같네요.

close #34

2023-05-08 16:25 UTC, soyi47 approved these changes
스타일드 컴포넌트 파일명 컨벤션 맞춰서 수정해줄거라 믿고 어프루브~ 👏👏👏

2023-05-08 16:25 UTC, soyi47 commented on packages/payment/src/components/Card/Card.stories.tsx
> +      cardNumber={11112}
얘 카드 번호 왜 넣다 말았어요? ㅋㅋㅋㅋㅋㅋ 작은 카드는 번호 나오다 말길래 문제 있는 줄 알았슴다 ㅋㅋㅋㅋㅋ

2023-05-08 16:25 UTC, soyi47 commented on packages/payment/src/components/Card/style.ts
> +};
👍👍👍

2023-05-09 08:46 UTC, yunjin-kim commented on packages/payment/src/components/Card/Card.stories.tsx
> +      cardNumber={11112}
숫자가 입력되는 과정을 보여주려고 했습니다ㅋㅋ

2023-05-14 13:15 UTC, liswktjs requested changes
윤진킴 카드 뽑았다~

2023-05-14 13:15 UTC, liswktjs commented on packages/payment/src/components/Card/Card.stories.tsx
> +      ownerName={'김윤진'}
윤진씨 카드군요 ㅋㅋㅋㅋㅋㅋㅋㅋ 괜히 웃기네요  그런데 디자인 시스템 배포 될 예정인데 실명 들어가도 상관 없으신가요? ㅋㅋㅋㅋ

2023-05-14 13:15 UTC, liswktjs commented on packages/payment/src/components/Card/Card.styled.ts
> +  }
카드 사이즈는 정말.... custom하게 해주지 맙시다 이게 좋을듯 하핫 👍

2023-05-14 13:15 UTC, liswktjs commented on packages/payment/src/components/Card/Card.stories.tsx
> +      cardType={{ name: '하나카드', color: 'green' }}
이 요소들은 storybook에서 직접 바꿔서 값 넣어볼 수 있게 해주는게 좋을 것 같습니다!

2023-05-14 13:15 UTC, liswktjs commented on packages/payment/src/components/Card/Card.tsx
> +        <CardNumber size={size}>{cardNumbers[3].replace(/./g, '*')}</CardNumber>
요기는 ref 까지는 굳이 넣어줄 필요 없겠죠? 궁금하네요 필요성의 여부... 어떻게 생각하시나요?

2023-05-15 07:40 UTC, yunjin-kim commented on packages/payment/src/components/Card/Card.stories.tsx
> +      ownerName={'김윤진'}
저를 더 알리고 좋은거죠~

2023-05-15 07:41 UTC, yunjin-kim commented on packages/payment/src/components/Card/Card.tsx
> +        <CardNumber size={size}>{cardNumbers[3].replace(/./g, '*')}</CardNumber>
넣어줘야 하는 이유가 있나요?

2023-05-21 09:57 UTC, merged