feat: 장바구니 공통 컴포넌트를 개발한다
dry-frontend/dry-design-system pull request #5
Opened 2023-04-20 11:38 UTC by notPotter

## 구현내용 

공통 버튼 컴포넌트를 구현한다. 

- [x] `variant` props로 버튼 상태(primary, secondary, plain)을 설정할 수 있다.
- [x] `size` props로 버튼 사이즈를 설정할 수 있다.

대면으로 코드 리뷰 진행하여, 간단히 PR 메시지 남겼습니다.

2023-04-20 11:49 UTC, moonheekim0118 approved these changes
해리 수고하셨습니다!
별도 수정사항 없을 것 같아서 바로 어프루브 할게요!

나중에 버튼 px 사이즈만 픽스되면 수정해요~

2023-04-20 11:49 UTC, moonheekim0118 commented on packages/cart/package.json
> +    "framer-motion": "^10.12.2"
👍

2023-04-20 11:49 UTC, moonheekim0118 commented on packages/cart/src/components/Button/Button.tsx
> +        <p style={{ margin: '0' }}>{children}</p>
p 태그는 스타일이 margin 하나 밖에 없어서 styled component로 만들지 않으신걸까요? 어떤걸 styled component 로 분리할 것과 아닌 것의 기준이 있으면 좋을 것 같아요.

2023-04-20 11:49 UTC, moonheekim0118 commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = 'submit' | 'button' | 'reset';
💯

2023-04-20 11:57 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +        <p style={{ margin: '0' }}>{children}</p>
이건 수정하도록 하겠습니다!
모든 컴포넌트를 분리하는게 뒤에 기준점 관련으로 곤란하지 않을 것 같네요!

2023-04-23 07:15 UTC, al-bur commented on packages/cart/src/components/Button/Button.tsx
> +  type = 'submit',
Button의 type을 기본으로 submit으로 해놓은 이유가 있을까요???

2023-04-23 07:17 UTC, al-bur commented on packages/cart/src/components/Button/Button.tsx
> +  prefixIconURL?: string;
해당 props의 네이밍이 URL로 끝나는 것에 대해서 이유를 알 수 있을까요??

storybook 사용처를 보면 svg를 넘겨주는 것으로 보이는 데 특정하게 url이라고 해줄 이유가 있을까 생각이 듭니다

2023-04-23 07:21 UTC, al-bur commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = 'submit' | 'button' | 'reset';
`export declare type ButtonType = 'submit' | 'button' | 'reset';`

이 타입 같은 경우는 기존에 react 같은 라이브러리에서 제공하는 타입은 없는 걸까요??
ButtonType의 역할 같은 경우는 button tag에 적용될 type attribut를 제한 하는 용도일 텐데, 만약 추후에 현재는 3개의 attribute만 존재하다가 이후에 해당 attributes가 바뀌게 된다면 저희는 다시 이 코드를 수정해줘야할듯합니다.

근데, react 라이브러리나 다른 곳에서 이미 관리를 해주고 있는 타입이 있다면 우리가 그 타입을 사용하고 추후에도 해당 타입이 자동으로 관리되게 해줄 수 있지 않을까 생각을 했습니다.

2023-04-23 07:25 UTC, al-bur commented on packages/cart/src/components/LoadingSpinner/styles.ts
> +`;
button에서는 S. prefix를 사용하는데 여기서는 S prefix를 사용하지 않는데 무슨 차이가 있을까요??

2023-04-23 07:25 UTC, al-bur reviewed
해리~ 고생했어요!! 
몇 가지 코멘트 남겼습니다ㅎㅎ

2023-04-23 07:39 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +  prefixIconURL?: string;
icon이라고만 하면 <img> 엘리먼트 등을 넘길 수도 있다라는 착각을 하지 않을까 싶어서
좀 더 분명하게 알려주고자 URL을 붙이게 되었습니다!

2023-04-23 07:44 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +  type = 'submit',
기본적으로 Button의 type이 submit이라 동일하게 설정해두었습니다!

https://developer.mozilla.org/en-US/docs/Web/HTML/Element/button

2023-04-23 07:46 UTC, notPotter commented on packages/cart/src/components/LoadingSpinner/styles.ts
> +`;
`Spinner`는 단독으로 스타일을 정의하고 있어서 따로 S 객체를 만들지 않았는데
혼란이 있을 수 있겠네요! S 객체 안에 스타일을 정의하는 것으로 통일하겠습니다!

2023-04-23 07:55 UTC, notPotter commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = 'submit' | 'button' | 'reset';
음... 제가 약간 이해를 못한 것 같습니다.

> 추후에 현재는 3개의 attribute만 존재하다가 이후에 해당 attributes가 바뀌게 된다면 저희는 다시 이 코드를 수정해줘야할듯합니다.

버튼 요소에서 제공하는 type이 3가지 밖에 없는데 이후에 attributes가 바뀌게 된다는 게 무슨 말씀이실까요??
만약 type이 추가로 생기거나 변화될 수도 있다는 말씀이실까요?

2023-04-23 08:04 UTC, al-bur commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = 'submit' | 'button' | 'reset';
> 만약 type이 추가로 생기거나 변화될 수도 있다는 말씀이실까요?

맞습니다 근데 아예 일어나지 않을 확률일 것 같긴 하네요ㅎㅎ
제가 했던 이야기는 저희가 직접 관리해야하는 포인트들을 최대한 줄이는 게 나중에 유지보수하기 편하지 않을까 생각을 했었어요!

찾아보니, react type에서 이렇게 제공을 해주는 것 같더라고요! 그래서, button type attribute에 대한 타입 정의는 react 팀이 알아서 하게 만들어 버리면 저희가 해당 타입에 대해서 유지보수 해줄 필요가 없지 않을까하는 이야기였습니다!
`type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement>['type'];`

근데, 해리가 말해준 것처럼 사실 button type attribute가 변화하지는 않을 것 같긴하네요!

2023-04-23 08:05 UTC, al-bur commented on packages/cart/src/components/Button/Button.tsx
> +  type = 'submit',
그러게요 왜 기본을 submit으로 해놓았을까 궁금하긴 하네요ㅎㅎ꼼꼼함 좋은 것 같습니다

2023-04-23 08:48 UTC, al-bur commented on packages/cart/src/components/LoadingSpinner/styles.ts
> +`;
네네!! 아니면 뭔가 따로 spinner 컴포넌트를 하나 더 만들어서 다른 컴포넌트에서도 재활용 될 수 있도록 해줘도 좋지 않을까 생각을 했어요~

2023-04-23 09:04 UTC, al-bur commented on packages/cart/src/components/Button/Button.tsx
> +  prefixIconURL?: string;
이해했습니다!!

근데, 궁금한 것이 엘리먼트는 못 받게 하는 건가요????
엘리먼트가 아닌 string으로 받으려고 하게 된 이유가 있을까요?

2023-04-24 04:55 UTC, notPotter commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = 'submit' | 'button' | 'reset';
`type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement>['type'];`

좋네요! 수정하도록 하겠습니다~

2023-04-24 04:57 UTC, notPotter commented on packages/cart/src/components/LoadingSpinner/styles.ts
> +`;
spinner가 일단은 디자인시스템 범위에 들어가지 않아서
버튼에서 사용만 고려해서 만들어봤습니다! 재사용은 추후에 논의 후에 발전시켜보는 게 좋을 것 같아요!

2023-04-24 04:58 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +  prefixIconURL?: string;
icon의 style을 일관적으로 하고 싶다는 생각입니다!
엘리먼트로 받게되면 버튼마다 icon의 사이즈나 스타일이 다를 수 있는데 
이가 나쁜 UX로 이어질 수 있지 않을까라고 생각했습니다!

2023-04-24 04:59 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +  type = 'submit',
라이브러리를 따르는 게 더 좋아보이긴 하네요!
어찌됐든 저희도 라이브러리를 만드는 거니까요!

2023-04-24 06:37 UTC, al-bur commented on packages/cart/src/components/LoadingSpinner/styles.ts
> +`;
네 좋습니다!

2023-04-24 06:38 UTC, al-bur commented on packages/cart/src/components/Button/Button.tsx
> +  prefixIconURL?: string;
오호 그렇네요! 컴포넌트로 받아버리면 ui가 어떻게 깨질 수 있는 지 모르겠네요ㅎㅎ
너무 좋은 것 같습니다!

2023-04-24 06:38 UTC, al-bur approved these changes
LGTM~ 고생했어요

2023-04-25 03:29 UTC, compy-ryu requested changes
해리 첫빠따로 고생 많으십니더 허허...

저도 마참내 배포가 끝나서 뒷북 리뷰 살짝 남겨봅니더!!
확인 후 반영 or 댓글 부탁드려유!!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +      line-height: 89%;
범용적으로 쓰일 컴포넌트에 너비, 높이를 주는 행위는 컴포넌트 재사용성을 매우 떨어뜨리게 되어유.

가능한 padding, width 100%으로 주고, 컴포넌트를 사용하는 곳에서 width 값을 스타일로 주거나
혹은 상위 컴포넌트의 너비를 조정 or grid / flex로 적절히 사이즈를 제어하는 것이 좋슴당

그러니 width, height 날리고 padding으로 피그마 시안 높이 맞추는 것을 권장드립니더.

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +      line-height: 89%;
line-height는 100% 이하로 가지 않는 것이 좋습니다.

만약 버튼에 여러 라인을 넣었을 때 겹칠 수 있고, 혹은 폰트가 바뀌었을 때 고려해야할 점이 많아집니다.
또, 일부 환경 / 사용케이스에 따라 글씨가 잘려보일 수 있어요!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +
PrefixIcon은 img가 아니라, svg로 처리하는건 어떨까유
FontAwsome이란 무료 아이콘 라이브러리가 있는데, 요걸 쓰면 디자이너와 협업하기도 좋슴덩

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +export const ButtonStyles = {
요 부분, 반환 타입을 달아주거니 또는 Button 컴포넌트 Props interface에서 요거 keyof로 키값들 뽑아내서 타입 재활용하면 Button 타입들 세세히 다시 선언 안해도 돼서 좋을거 같슴더!!

관리 포인트 줄이고 개발자의 실수를 최대한 줄여봅쉬더!!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +
```tsx
${({ disabled }) => disabled && css`
      cursor: not-allowed;
      opacity: 0.6;
`}
```

이렇게 하는건 어떻게 생각하시나유!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement>['type'];
진자 진자 별건 아닌디... 또 한번 감싸서 추상화하는거보다는 prop 쪽에서 고대로 뽑아서 표현해주는게 더 좋을 것 같은데 어떻게 생각하시나유!!!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/Button.tsx
> +  size = 'small',
전 개인적으로 size default 값은 medium이 기본적으로 연상되는것 같읍니다.. 
작디 작은.. 뇌피셜입니다.

일단 size prop 없이 써보고 어 너무 크네.. 줄여야지 했는데 그대로면 슬플거 같아유

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +  `,
요거 Button 컴포넌트에서 스타일 포함하지 않고 다시 감싼 이유가 궁금헙니더!!

2023-04-25 03:29 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +    }}
```suggestion
    ${({ size }) => (ButtonStyles.Size[size])
```

![8k4n4JEsl8](https://user-images.githubusercontent.com/94832610/234167439-f3e596cd-d9ed-4979-bc69-5097b6a94419.jpeg)



위 피드백들 반영하심 이렇게 쓰실 수 있어유!

2023-04-25 03:36 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +      line-height: 89%;
동의합니다. 이전 figma 스타일에 있어서
일단 figma대로 하는게 맞겠지..? 하면서 적용한 스타일이었습니다!

2023-04-25 03:40 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +      line-height: 89%;
음.. 사용처에서 좀 더 유연하게 사용하려면 확실히 콤피 말씀대로 하는 것이 좋을 것 같네요!

2023-04-25 03:41 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +
더 간결하고 좋네요!

2023-04-25 03:50 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +      line-height: 89%;
맞숩니더!!

width: 100%는 제 기억상 안 넣어도 알아서 100% 채워졌던거로 기억합니더!
아마도 padding 만 넣어주셔도 알잘딱깔센하게 잘 표시될꺼에유

2023-04-25 04:49 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +
svg.. 아직 제대로 다뤄본 적이 없어서 공부해보고 반영해보겠습니다!

2023-04-25 04:49 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +  `,
이건 스타일 변경 과정에서 남긴 실수 같네요! 제거 하겠습니다!

2023-04-25 04:56 UTC, notPotter commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement>['type'];
```
export declare type ButtonVariant = keyof typeof ButtonStyles.Type;
export declare type ButtonSize = keyof typeof ButtonStyles.Size;
```

이렇게 수정하자는 말씀맞으신가요?

2023-04-25 04:58 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +export const ButtonStyles = {
```typescript
export declare type ButtonVariant = keyof typeof ButtonStyles.Type;
export declare type ButtonSize = keyof typeof ButtonStyles.Size;
```

위와 같이 수정해보았습니다!

2023-04-25 04:59 UTC, notPotter commented on packages/cart/src/components/Button/Button.tsx
> +  size = 'small',
음 저는 default에 대한 기호가 없어서 일단 가장 빈번하게 사용될 것 같은
medium으로 변경해두겠습니다!

2023-04-25 05:03 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +    }}
```tsx
${({ variant }) => ButtonStyles.Type[variant]}

${({ size }) => ButtonStyles.Size[size]}

${({ disabled }) =>
  disabled &&
  css`
    cursor: not-allowed;
    opacity: 0.6;
`}
```

확실히 깔끔해졌네요!

2023-04-25 07:11 UTC, notPotter commented on packages/cart/src/components/Button/styles.ts
> +
콤피 혹시 지금처럼 string으로 받아서 svg로 변환하자는 말씀이신가요?
아니면 처음부터 svg를 컴포넌트 형식으로 prop으로 전달 받아서 렌더링을 하자는 말씀이신가요?

제가 찾아본 결과로는 
1번 방법의 경우는 지나치게 번거로운 방식 (DOMParser.. 등등)인 것 같고
2번 방법의 경우는 사용자가 svg를 컴포넌트 형식으로 보내줘야하는데 이는 앨버한테 말씀드렸듯이 외부에서 스타일을 조작해서 일관적인 UX를 제공하지 못하는 문제가 있을 것 같습니다!

혹시 알고 있는 다른 방법이 있다면 알려주시면 감사하겠습니다.

2023-04-25 12:32 UTC, compy-ryu approved these changes
해리 제 훈수들을 참아주어서 증말 증말 감사합니더.
몇가지 코멘트 더 달아보았는디, 이건 사실 취향의 영역이라 반영하셔도 안하셔도 아무런 상관 없슴덩

approve 눌러놓을꼐유!!
고생하셨읍니더!!

2023-04-25 12:32 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +export const ButtonStyles = {
오, 맞아유 이 뜻입니더!
그런데 이렇게 keyof typeof로 뽑아내면 type.d.ts로 뽑아내는게 좋을지

약간 고민되네유.
props 인터페이스에서 바로 선언하고, 해당 타입만 만약 필요하면 ButtonProps['size']
이런식으로 사용하는게 네이밍상 좋을 것 같기도해서유!

물론 비슷한 것끼리 분리하고 모아두는 것이 좋다 생각도 드는데

최근 들어 또 드는 생각은 세세하게 분리된 것들을 보면
오히려 여기저기 왔다갔다하면서, 그 컨벤션을 지키는게 피로감으로 다가오더라구요.

해리 생각은 어떤가유?

2023-04-25 12:32 UTC, compy-ryu commented on packages/cart/src/components/Button/styles.ts
> +
이 부분은 제가 너무 막연하게 설명한 것 같네요!!

요거 제가 작업할 때 예시 세팅해둘께유!! 일단 넘어가시쥬!

2023-04-25 12:32 UTC, compy-ryu commented on packages/cart/src/components/Button/types.d.ts
> +export declare type ButtonType = React.ButtonHTMLAttributes<HTMLButtonElement>['type'];
오, ButtonType 말한거였어요!
ButtonProps에서 type에 고대로 넣어주어도 될 것 같단 뜻이였어유!

ButtonType은 ButtonProps 뺴고 사용처가 없어서요!
위 리뷰와 살짝 이어집니다.

2023-04-26 05:45 UTC, merged